spring.application.name=taskmanager

jwt.secret=Ho8WZAD0YzeqoV/DWkGvYDktVGVam2K82df1f2ntkQM=

spring.datasource.url=jdbc:mysql://localhost:3306/taskmanager
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

server.port=8080